### ISSUE TITLE
Can't bump version number

### ISSUE THREAD

**Issue by gforsyth** [regro/rever#101]
I'm probably doing something wrong, but trying to push a new release of `xonda` and it seems dead set on remaining version 0.2.2

```
gil@bad_cat ~/git/xonda master 🐚  rever 0.3
Activity 'changelog' has already been completed!
Activity 'conda_forge' has already been completed!
Activity 'ghrelease' has already been completed!
Activity 'tag' has already been completed!
Activity 'version_bump' has already been completed!
activity-start:pypi:starting activity pypi
running sdist
running egg_info
creating xonda.egg-info
writing xonda.egg-info/PKG-INFO
writing dependency_links to xonda.egg-info/dependency_links.txt
writing top-level names to xonda.egg-info/top_level.txt
writing manifest file 'xonda.egg-info/SOURCES.txt'
reading manifest file 'xonda.egg-info/SOURCES.txt'
writing manifest file 'xonda.egg-info/SOURCES.txt'
running check
creating xonda-0.2.2
creating xonda-0.2.2/xonda.egg-info
creating xonda-0.2.2/xontrib
copying files to xonda-0.2.2...
copying setup.py -> xonda-0.2.2
copying xonda.egg-info/PKG-INFO -> xonda-0.2.2/xonda.egg-info
copying xonda.egg-info/SOURCES.txt -> xonda-0.2.2/xonda.egg-info
copying xonda.egg-info/dependency_links.txt -> xonda-0.2.2/xonda.egg-info
copying xonda.egg-info/not-zip-safe -> xonda-0.2.2/xonda.egg-info
copying xonda.egg-info/top_level.txt -> xonda-0.2.2/xonda.egg-info
copying xontrib/xonda.xsh -> xonda-0.2.2/xontrib
Writing xonda-0.2.2/setup.cfg
creating dist
Creating tar archive
package init file 'xontrib/__init__.py' not found (or not a regular file)
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

removing 'xonda-0.2.2' (and everything under it)
running upload
Submitting dist/xonda-0.2.2.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): File already exists.
error: Upload failed (400): File already exists.
activity-error:pypi:activity failed with execption:
Traceback (most recent call last):
  File "/home/gil/miniconda3/lib/python3.6/site-packages/rever/activity.xsh", line 62, in __call__
    self.func(*args, **kwargs)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/rever/activities/pypi.xsh", line 84, in _func
    p = ![$PYTHON setup.py @(commands)]
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19376, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19339, in run_subproc
    command.end()
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12645, in end
    self._end(tee_output=tee_output)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12664, in _end
    self._raise_subproc_error()
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12774, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['/home/gil/miniconda3/bin/python', 'setup.py', 'sdist', 'upload']' returned non-zero exit status 1.
rewinding to 860bf3cfc7557bb7a419a97ef08a061c87d9ef61
```

**Comment by CJ-Wright** [comment]
@gforsyth Thank you for reporting! @scopatz do you know what might be happening? (I haven't done that much work on the pypi system).

Has the version been bumped to 0.3 in the source code?

**Comment by gforsyth** [comment]
In the `setup.py` file?  I thought that `rever` handled that replacement?
There's no other version number in the code -- it's an implicit namespace package so no `__init__.py`

**Comment by CJ-Wright** [comment]
yes, it should have done a replacement in the `setup.py` file. Was it successful?

**Comment by scopatz** [comment]
Hi @gforsyth @CJ-Wright - It looks like the bug with not running commands that were completed on previous builds is what is to blame here. (We have fixed this in rever master.) The whole repo seems to still be at 0.2.2 still.  Temporarily you can work around this by `rm -r rever/`, to clear the log.

**Comment by scopatz** [comment]
Maybe we should put out a new rever version?

**Comment by CJ-Wright** [comment]
Yep we should do another release.

**Comment by scopatz** [comment]
Ok rever 0.2.5 has been released. You probably need to adjust the rever.xsh file to use the new `push_tag` activity.

**Comment by gforsyth** [comment]
Thanks @scopatz and @CJ-Wright ! New release and the `push_tag` activity seem to have done the trick.
