### ISSUE TITLE
BUG: conda-forge organization account?

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#110]
I got the following:
```sh
(regro) christopher@christopher-ubuntu ~/dev/xpdSim master $ rever -a conda_forge 0.1.2
activity-start:conda_forge:starting activity conda_forge
Fork doesn't exist creating feedstock fork...
activity-error:conda_forge:activity failed with execption:
Traceback (most recent call last):
  File "/home/christopher/dev/rever/rever/activity.xsh", line 62, in __call__
    self.func(*args, **kwargs)
  File "/home/christopher/dev/rever/rever/activities/conda_forge.xsh", line 147, in _func
    repo.create_fork(username)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/github3/decorators.py", line 33, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/github3/repos/repo.py", line 765, in create_fork
    json = self._json(resp, 202)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/github3/models.py", line 154, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/github3/models.py", line 176, in _boolean
    raise exceptions.error_for(response)
github3.exceptions.UnprocessableEntity: 422 'CJ-Wright' is the login for a user account. You must pass the login for an organization account.
rewinding to 8854a6547dcabc67c15cc605e41cf8b6f0827eb4
```

**Comment by CJ-Wright** [comment]
I think this is due to the project being camelcase and the feedstock being lower. Are all conda-forge repos lowercase?

**Comment by CJ-Wright** [comment]
This seems to work fine if I make certain I have a fork.

**Comment by scopatz** [comment]
Yes, I believe that all feedstocks are lowercase
