### ISSUE TITLE
BUG: version

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#114]
`rever 0.2.0` yields
```
Traceback (most recent call last):
  File "/home/christopher/mc/envs/dp_dev/bin/rever", line 3, in <module>
    main()
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/rever/main.xsh", line 219, in main
    env_main(args=args)
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/rever/main.xsh", line 213, in env_main
    run_activities(ns)
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/rever/main.xsh", line 129, in run_activities
    need, done = compute_activities_to_run()
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/rever/main.xsh", line 93, in compute_activities_to_run
    done = compute_activities_completed()
  File "/home/christopher/mc/envs/dp_dev/lib/python3.5/site-packages/rever/main.xsh", line 69, in compute_activities_completed
    entry['version'] == $VERSION):
KeyError: 'version'
```

**Comment by CJ-Wright** [comment]
`rever                     0.2.5                    py35_0    conda-forge`

**Comment by CJ-Wright** [comment]
removing rever dir fixed

**Comment by scopatz** [comment]
This is because the log format changed, right?

**Comment by CJ-Wright** [comment]
I guess, I'm not certain (I haven't ran it again yet)
