### ISSUE TITLE
Error running rever on regolith

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#120]
I got the following while bumping regolith
(regro) christopher@christopher-ubuntu ~/dev/regolith master $ rever 0.1.8
Traceback (most recent call last):
  File "/home/christopher/mc/envs/regro/bin/rever", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/christopher/dev/rever/scripts/rever", line 3, in <module>
    main()
  File "/home/christopher/dev/rever/rever/main.xsh", line 219, in main
    env_main(args=args)
  File "/home/christopher/dev/rever/rever/main.xsh", line 213, in env_main
    run_activities(ns)
  File "/home/christopher/dev/rever/rever/main.xsh", line 129, in run_activities
    need, done = compute_activities_to_run()
  File "/home/christopher/dev/rever/rever/main.xsh", line 93, in compute_activities_to_run
    done = compute_activities_completed()
  File "/home/christopher/dev/rever/rever/main.xsh", line 69, in compute_activities_completed
    entry['version'] == $VERSION):
KeyError: 'version'

**Comment by CJ-Wright** [comment]
Running on master rever

**Comment by CJ-Wright** [comment]
This is from using the old rever directory type, we may consider writing something to check this.
