### ISSUE TITLE
Error running PyPI activity (Windows)

### ISSUE THREAD

**Issue by igortg** [regro/rever#121]
I'm having the following error when running the PyPI activity:

```
activity-start:pypi:starting activity pypi
activity-error:pypi:activity failed with execption:
Traceback (most recent call last):
  File "W:\esss\envs\flask-rest-orm\lib\site-packages\rever\activity.xsh", line 62, in __call__
    self.func(*args, **kwargs)
  File "W:\esss\envs\flask-rest-orm\lib\site-packages\rever\activities\pypi.xsh", line 84, in _func
    p = ![$PYTHON setup.py @(commands)]
...
  File "W:\esss\envs\flask-rest-orm\lib\site-packages\xonsh\__amalgam__.py", line 19001, in run
    p = self._run_binary(kwargs)
  File "W:\esss\envs\flask-rest-orm\lib\site-packages\xonsh\__amalgam__.py", line 19022, in _run_binary
    raise XonshError(e)
xonsh.__amalgam__.XonshError: xonsh: subprocess mode: command not found: W:\work\envs♀lask-rest-orm\python.exe
```

Seems that xonsh is having problems with Windows paths. I reported the issue at xonsh/xonsh#2590, but maybe it is possible to workarround till we got a fix.

I could get PyPI activity to work by overriding the $PYTHON env on the rever.xsh

```
$PYTHON = 'python'
```

Awesome project guys. Thks to CJ-Wright for the tip.

**Comment by scopatz** [comment]
Thanks for reporting @igortg! this definitely seems like a xonsh error.
