### ISSUE TITLE
Rever doesn't write .authors.yml if error

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#178]
This means I can't fix the `.authors.yml` file.

```python
The email 'cjwright4242@gmail.com' is associated in version control with 'Christopher J. Wright', but is currently assigned to christopher.Please either add Christopher J. Wright as an alias to christopher in 'the authors file' with:

- name: christopher
  email: cjwright4242@gmail.com
  aliases:
    - Christopher J. Wright

or remove cjwright4242@gmail.com from christopher.
Traceback (most recent call last):
  File "/home/christopher/mc/envs/regro/bin/rever", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/christopher/dev/rever/scripts/rever", line 3, in <module>
    main()
  File "/home/christopher/dev/rever/rever/main.xsh", line 249, in main
    env_main(args=args)
  File "/home/christopher/dev/rever/rever/main.xsh", line 239, in env_main
    setup_activities(ns)
  File "/home/christopher/dev/rever/rever/main.xsh", line 181, in setup_activities
    status = act.setup()
  File "/home/christopher/dev/rever/rever/activity.xsh", line 124, in setup
    status = self._setup()
  File "/home/christopher/dev/rever/rever/activities/authors.xsh", line 187, in setup_func
    include_orgs)
  File "/home/christopher/dev/rever/rever/activities/authors.xsh", line 195, in _update_authors
    md = update_metadata(metadata)
  File "/home/christopher/dev/rever/rever/authors.xsh", line 292, in update_metadata
    raise RuntimeError("Duplicated author/email combos")
RuntimeError: Duplicated author/email combos
```

**Comment by scopatz** [comment]
Yeah, it means that you need to start the authors file. It could try to write down what it knows, though.

**Comment by CJ-Wright** [comment]
Yeah, I liked the previous version which wrote something for me to edit.
