### ISSUE TITLE
authors error?

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#180]
I got the following error with xpdAn:
```python
activity-start:authors:starting activity authors
wrote authors to AUTHORS
wrote authors since 0.4.0 to rever/LATEST-AUTHORS.json
wrote mailmap file to .mailmap
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Untracked files:
	.pytest_cache/
	docs/quickstart.rst
	docs/using_servers.rst
	examples/EuTiO3/
	examples/fake_xpd/run.xsh
	examples/hist_test.py
	examples/pipeline.py
	examples/pipeline2.py
	examples/profile.txt
	examples/profile2.txt
	examples/xpd_pipeline.pdf
	examples/xpd_pipeline2.pdf
	examples/xpd_pipeline_feb7.jpeg
	flake8.txt
	xpdan/startup/mystream.png
	xpdan/tests/mystream.png
	xpdan/tests/pipelines/mystream.png

nothing added to commit but untracked files present
activity-error:authors:activity failed with execption:
Traceback (most recent call last):
  File "/home/christopher/dev/rever/rever/activity.xsh", line 83, in __call__
    self.func(*args, **kwargs)
  File "/home/christopher/dev/rever/rever/activities/authors.xsh", line 152, in _func
    vcsutils.commit('Updated authorship for ' + $VERSION)
  File "/home/christopher/dev/rever/rever/vcsutils.xsh", line 37, in vcs_dispatcher
    return func(*args, **kwargs)
  File "/home/christopher/dev/rever/rever/vcsutils.xsh", line 126, in git_commit
    git commit -am @(message)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19783, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19746, in run_subproc
    command.end()
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12899, in end
    self._end(tee_output=tee_output)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12918, in _end
    self._raise_subproc_error()
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13039, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'commit', '-am', 'Updated authorship for 0.4.1']' returned non-zero exit status 1.
rewinding to 3e4480301d558483c0c7a24a88fbecc6375c8adf
```

It seems to think that it is an empty commit. Ah, this is most likely because the authorship of the previous was the same. Should we allow empty commits for this? Or should we wrap this in a try except.

**Comment by scopatz** [comment]
Ahhh yeah, if everything is exactly the same this could happen. We should allow empty commits
