### ISSUE TITLE
conda_forge activity: fail if smithy fails

### ISSUE THREAD

**Issue by dougalsutherland** [regro/rever#183]
Following up from #171: running the `conda_forge` activity, I just got

```
Rerendering the feedstock
Traceback (most recent call last):
  File "/Users/dougal/anaconda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/dougal/anaconda/lib/python3.6/site-packages/conda_smithy/cli.py", line 424, in main
    args.subcommand_func(args)
  File "/Users/dougal/anaconda/lib/python3.6/site-packages/conda_smithy/cli.py", line 292, in __call__
    exclusive_config_file=args.exclusive_config_file,
  File "/Users/dougal/anaconda/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1319, in main
    check_version_uptodate(r, "conda-smithy", __version__, error_on_warn)
  File "/Users/dougal/anaconda/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1243, in check_version_uptodate
    raise RuntimeError("{} Exiting.".format(msg))
RuntimeError: conda-smithy version in root env (3.2.13) is out-of-date (3.2.14). Exiting.
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 4 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 2.06 KiB | 2.06 MiB/s, done.
```

[This line](https://github.com/regro/rever/blob/3b5d43ace6150a5c02e080d11d94fd2c69ff0ac5/rever/activities/conda_forge.xsh#L210) should check that the command succeeded. Since I'm not very xonsh-knowledgeable, I'll let you do that. :)

**Comment by CJ-Wright** [comment]
Hmm, maybe the conda forge activity should run the `check_version_uptodate` function somwhere in the check to make certain that things are running properly.

**Comment by scopatz** [comment]
Yeah, ideally this would be a check
