### ISSUE TITLE
Syntax error from GHRelease

### ISSUE THREAD

**Issue by CJ-Wright** [regro/rever#188]
Seems I got a syntax error:
```python
Traceback (most recent call last):
  File "/home/christopher/mc/envs/regro/bin/rever", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/christopher/dev/rever/scripts/rever", line 3, in <module>
    main()
  File "/home/christopher/dev/rever/rever/main.xsh", line 251, in main
    with environ.context():
  File "/home/christopher/mc/envs/regro/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/christopher/dev/rever/rever/environ.xsh", line 268, in context
    setup()
  File "/home/christopher/dev/rever/rever/environ.xsh", line 246, in setup
    ${...}._defaults[key] = default() if callable(default) else default
  File "/home/christopher/dev/rever/rever/environ.xsh", line 46, in default_dag
    from rever.activities.ghrelease import GHRelease
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20568, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20284, in compile
    transform=transform)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20253, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20364, in _parse_ctx_free
    raise original_error from None
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20351, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/parsers/base.py", line 349, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/parsers/base.py", line 2760, in p_error
    column=p.lexpos))
  File "/home/christopher/mc/envs/regro/lib/python3.6/site-packages/xonsh/parsers/base.py", line 482, in _parse_error
    raise err
SyntaxError: /home/christopher/dev/rever/rever/activities/ghrelease.xsh:43:46: ('code: @(',)
    ![git archive -9 --format=tar.gz --prefix=@(folder_name)/ -o @(fname) @(tag)]
```
using master 8b35eae183c4a4ee2b1a57504a4258bdd9be5c07 with xonsh 0.7.7

**Comment by CJ-Wright** [comment]
Fixed by newer xonsh
