### ISSUE TITLE
Dependecy missing (ruamel.yaml) from conda pkg

### ISSUE THREAD

**Issue by kcpevey** [regro/rever#198]
I installed `rever` from conda-forge. All seemed well until I added the authors activity to the rever.xsh and ran `rever setup`. When I ran that, I got an error due to the missing module:  
  
```
(base) conda_package $ rever setup
Traceback (most recent call last):
  File "//miniconda3/bin/rever", line 3, in <module>
    main()
  File "//miniconda3/lib/python3.7/site-packages/rever/main.xsh", line 252, in main
    env_main(args=args)
  File "//miniconda3/lib/python3.7/site-packages/rever/main.xsh", line 242, in env_main
    setup_activities(ns)
  File "//miniconda3/lib/python3.7/site-packages/rever/main.xsh", line 184, in setup_activities
    status = act.setup()
  File "//miniconda3/lib/python3.7/site-packages/rever/activity.xsh", line 124, in setup
    status = self._setup()
  File "//miniconda3/lib/python3.7/site-packages/rever/activities/authors.xsh", line 187, in setup_func
    include_orgs)
  File "//miniconda3/lib/python3.7/site-packages/rever/activities/authors.xsh", line 195, in _update_authors
    md = update_metadata(metadata)
  File "//miniconda3/lib/python3.7/site-packages/rever/authors.xsh", line 291, in update_metadata
    y, yaml = load_metadata(filename, return_yaml=True)
  File "//miniconda3/lib/python3.7/site-packages/rever/authors.xsh", line 133, in load_metadata
    yaml = YAML()
  File "//miniconda3/lib/python3.7/site-packages/lazyasd.py", line 97, in __call__
    obj = self._lazy_obj()
  File "//miniconda3/lib/python3.7/site-packages/lazyasd.py", line 64, in _lazy_obj
    obj = d['load']()
  File "//miniconda3/lib/python3.7/site-packages/rever/authors.xsh", line 17, in YAML
    from ruamel.yaml import YAML as y
ModuleNotFoundError: No module named 'ruamel.yaml'
```
  
I conda installed `ruamel.yaml` and no longer had the error. It seems it was just left out of the conda package?

**Comment by scopatz** [comment]
ahh sorry about this! it should be fixed if you reinstall now!
