### ISSUE TITLE
rever release failing on windows with permissions errors

### ISSUE THREAD

**Issue by sbillinge** [regro/rever#204]
The same release runs on a mac computer.  Here is the stack dump:
```
Activity 'version_bump' has already been completed!
activity-start:changelog:starting activity changelog
activity-error:changelog:activity failed with execption:
Traceback (most recent call last):
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\rever\activity.xsh", line 62, in __call__
    self.func(*args, **kwargs)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\rever\activities\changelog.xsh", line 101, in _func
    merged = self.merge_news(news=news, ignore=ignore)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\rever\activities\changelog.xsh", line 115, in merge_news
    with open(fname) as f:
PermissionError: [Errno 13] Permission denied: 'news\\rever'
rewinding to 0555dd229dcd6dc30400b7e4aedab685b401396d
```

Any thoughts?

**Comment by sbillinge** [comment]
@scopatz @CJ-Wright do you have thoughts on this?  I can't release my pytentiostat project right now.

**Comment by CJ-Wright** [comment]
What are the permissions on that file/folder? Can you open it in a regular python session?

**Comment by sbillinge** [comment]
pycharm can read and write files in both ``news`` and in ``news\rever``.   Also I can open and read a file in the ``news\rever`` directory ok using ipython.

Another question....why is rever writing a rever directory into my news directory?  Shouldn't it just be deleting all the rst files in there except the template?

**Comment by CJ-Wright** [comment]
I think it is trying to read the file not write it

**Comment by sbillinge** [comment]
python can read the file.  But rever created an empty ``/rever`` directory
in ``/news/`` when I tried to run the release from my windows
machine.  @chiahaoliu successfully did a release with the same xsh file
from a Linux box, so  it seems that something in there is getting confused
with the windows OS.
