### ISSUE TITLE
AssertionError from xonsh running rever

### ISSUE THREAD

**Issue by asmeurer** [regro/rever#240]
This is from running `rever 1.2` in https://github.com/deshaw/versioned-hdf5/pull/151

```pytb
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/bin/rever", line 6, in <module>
    from rever.main import main
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 24307, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23992, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 23952, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 24076, in _parse_ctx_free
    tree = self.parser.parse(
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/parsers/base.py", line 497, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2221, in p_atom_expr
    p[0] = self.apply_trailers(p[1], p[2])
  File "/Users/aaronmeurer/anaconda3/envs/versioned-hdf5/lib/python3.9/site-packages/xonsh/parsers/base.py", line 2215, in apply_trailers
    assert False
AssertionError
```

**Comment by asmeurer** [comment]
```
$ xonsh --version
xonsh/0.9.24
$ conda list rever
# packages in environment at /Users/aaronmeurer/anaconda3/envs/versioned-hdf5:
#
# Name                    Version                   Build  Channel
rever                     0.4.8                      py_0    conda-forge
```

**Comment by asmeurer** [comment]
Looks like this is https://github.com/xonsh/xonsh/issues/3888. Downgrading to Python 3.8 fixed it.
