### ISSUE TITLE
Rever fails on conda-forge task if user hasn't already forked feedstock

### ISSUE THREAD

**Issue by gforsyth** [regro/rever#96]
`xonda` is using `rever` now thanks to @CJ-Wright and also has a brand new conda package, so I've never updated it manually (and @CJ-Wright submitted the recipe).  

On running a release I get:
```
wrote /home/gil/.config/rever/github/gforsyth-xonda.cred
secured permisions of /home/gil/.config/rever/github/gforsyth-xonda.cred
Cloning into 'rever/xonda-feedstock'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
activity-error:conda_forge:activity failed with execption:
Traceback (most recent call last):
  File "/home/gil/miniconda3/lib/python3.6/site-packages/rever/activity.xsh", line 62, in __call__
    self.func(*args, **kwargs)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/rever/activities/conda_forge.xsh", line 136, in _func
    p = ![git clone @(origin) @(feedstock_dir)]
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19376, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19339, in run_subproc
    command.end()
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12645, in end
    self._end(tee_output=tee_output)
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12664, in _end
    self._raise_subproc_error()
  File "/home/gil/miniconda3/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 12774, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'clone', 'git@github.com:gforsyth/xonda-feedstock.git', 'rever/xonda-feedstock']' returned non-zero exit status 128.
```

Since user has already entered credentials for github, can the fork of the feedstock be automated?

**Comment by CJ-Wright** [comment]
This should be possible
http://github3py.readthedocs.io/en/master/repos.html?highlight=fork#github3.repos.repo.Repository.create_fork

**Comment by scopatz** [comment]
Thanks for pointing this out @gforsyth!
